pipelines:
  - name: local_pipe
    steps:
      - name: local_pipe
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
